### ISSUE TITLE
MoPub Not defined

### ISSUE THREAD

**Issue by TheRealKev1n** [floatinghotpot/cordova-plugin-mopub#12]
Hi,

I used the code and replaced the banner codes to my own. but everytime i click something i get

Uncaught ReferenceError: MoPub is not defined at file:///android_asset/www/index.html:98

And its not showing ads..

**Comment by rusboard** [comment]
Same for me.

**Comment by floatinghotpot** [comment]
Possible reason is that the plugin is not installed properly.

See this issue and its answers, hope it helps.

https://github.com/floatinghotpot/cordova-admob-pro/issues/115

**Comment by rusboard** [comment]
My problem was that in app already was installed AdMob plugin with some version of Google Play Service. I removed this plugins and install again MoPub plugin and all good.

So, I thinks that problem was in different versions of Google Play Services plugins.
