### ISSUE TITLE
Do I need add addition modules that show AdMob?

### ISSUE THREAD

**Issue by rusboard** [floatinghotpot/cordova-plugin-mopub#13]
Do I need add addition modules that show AdMob ad through your MoPub module?
Because in logcat I see that you plugin trying to find AdMob libraries and can't.

**Comment by floatinghotpot** [comment]
please paste some screenshots or logs ...

**Comment by rusboard** [comment]
Yes, sure.

![screen](https://cloud.githubusercontent.com/assets/5380762/7295682/3a40cec0-e9c1-11e4-9883-9f3c35d208af.png)

**Comment by rusboard** [comment]
And screen of my Cordova plugins that installed fro this app.
![screen2](https://cloud.githubusercontent.com/assets/5380762/7295716/885a5db0-e9c1-11e4-8a5c-180057942568.png)

**Comment by floatinghotpot** [comment]
It's just okay if only see it attempts to find google play services RESOURCES, cause it did not come witht he google-play-services.jar. You can safely ignore it, according to answer from google support team.

**Comment by rusboard** [comment]
Thank you for quick answer. Will try tp debug on MoPub page or AdMob.

**Comment by rusboard** [comment]
So, what can I say.
Your plugin working only with MoPub native ad (only ad that was created in MoPub).

Plugin can't show ad if this ad showing through other networks that integrated in MoPub.
For example: If I will create MoPub order (ad) that will get ad from AdMob or from Chartboost - your plugin will not show this ad. Because for this networks need additional SDK's.

**Comment by floatinghotpot** [comment]
you are correct, this plugin only comes with the basic mopub sdk, not with other sdks.
