### ISSUE TITLE
Very low fill rate <5%

### ISSUE THREAD

**Issue by ESA14** [floatinghotpot/cordova-plugin-mopub#14]
Hello,

I currently have a very low fill rate in my app, down to 2%.
Do you have normal fill rates with this plugin?

I use this code to show interstitials after a new page is loaded:
if(MoPub) MoPub.prepareInterstitial( {adId:adid.interstitial, autoShow:true} );

Do you think I get a higher fill rate if I change autoShow to false and load the ad before the page change?

Thanks

**Comment by floatinghotpot** [comment]
I think it's related with the ad service. Try changing to google admob, the fill rate is always higher than 95%, they also pay much faster.
