### ISSUE TITLE
ReferenceError: MoPub is not defined IONIC

### ISSUE THREAD

**Issue by rafasegat** [floatinghotpot/cordova-plugin-mopub#15]
Hi guys,

Im using cordova-plugin-mopub at ionic and installed all correctly but when I try to emulate shows the error ReferenceError: MoPub is not defined

Should I do something different at ionic?

Im emulating at Google Chrome as cmd ionic serve --lab

Thanks
Raf

**Comment by floatinghotpot** [comment]
The plugin contains native code, you have to add it and build into app to make it work. 

Emulate in browser only display the html content but cannot run the native code.

BTW, AdMob is more recommended for its high fill rate, good support and fast payment.

**Comment by rafasegat** [comment]
Hi!

Thanks so much for your response.

As run in browser or directly at Android still occur this error :(

Am I doing smthing wrong??

I already installed all plugins..

Cheers
Raf

**Comment by rafasegat** [comment]
As I know shouldnt occur this error. Independently if is browser or android should find this library MoPub...

**Comment by rafasegat** [comment]
Oh I got it!

I forgot to place it inside deviceready..

Thanks
Great plugin!
