### ISSUE TITLE
Update the SDK Google Play is rejecting apps installed with the plugin

### ISSUE THREAD

**Issue by deangelo200** [floatinghotpot/cordova-plugin-mopub#25]
Update the SDK Google Play is rejecting apps installed with the plugin
Look at the image attached 
[https://www.dropbox.com/s/j69unoid6in30nt/Screen%20Shot%202017-01-04%20at%204.45.10%20PM.png?dl=0](url)

**Comment by deangelo200** [comment]
Hello

**Comment by raytrask** [comment]
Please check out [this other issue](https://github.com/floatinghotpot/cordova-plugin-mopub/issues/23).  We got ours to work by getting the plugin from the git repo.

Good Luck

**Comment by hodaifa82** [comment]
@raytrask  @floatinghotpot  i got this message after installing the new version 

Error: Unable to build; intelxdk.config.additions.xml file includes plugin tags, which are no longer supported. Use the Intel XDK plugin manager to resolve this issue. See https://software.intel.com/en-us/xdk/docs/add-manage-project-plugins#additions-plugin-tags
Error: Could not retrieve plugin dependencies for MoPub'.
Error: Plugin MoPub failed to install.

**Comment by floatinghotpot** [comment]
Plugin updated to support latest MoPub iOS SDK via Cocoapod. 

Tested and published to npm as: cordova-plugin-mopub@2.4.0. 

Close this issue tracker.
