### ISSUE TITLE
No Ads found

### ISSUE THREAD

**Issue by optikalefx** [floatinghotpot/cordova-plugin-mopub#5]
I'm not sure what the issue is here.  If I run your test Ad ID

```
MoPub.prepareInterstitial({adId: "agltb3B1Yi1pbmNyDAsSBFNpdGUYsckMDA", autoShow: false});
```

It works fine.

If I try to run this with mine

```
MoPub.prepareInterstitial({adId: "b3252496cb2d4718aedb26ccc31a532f", autoShow: false});
```

I get 

```
error: 0, reason: No ads found., adNetwork:MoPub, adType:interstitial, adEvent:onAdFailLoad
```

You can see my ad here in my account http://cl.ly/image/020M1C0H2U03   And the code integration page here http://cl.ly/image/1t2D1H3r1J13

Not sure why it says no ads.

**Comment by Adriano21** [comment]
We implemented the mopub SDK and we are not seeing any ads. No adrequests and no ad impressions are coming through it. See logs below. Can someone help?

MoPub﹕ Failed to retrieve GPS location: access appears to be disabled.
I/MoPub﹕ Ad failed to load.
 Ad failed to load.
System.out﹕ mopub_failed_reason::NO_FILL
System.out﹕ mopub_ordinal::0

**Comment by floatinghotpot** [comment]
Usually NO_FILL means not proper ad resource is available in their Ad repository.

BTW, Google AdMob is more recommended, as their fill rate is nearly 100%, which means your requests can always be filled.

**Comment by optikalefx** [comment]
@floatinghotpot for the purposes of helping the programming community, could you add a disclaimer at the top of the readme about the fill rate? I know you probably don't want to inject an opinion, but trust me it's warranted when doing research.

**Comment by floatinghotpot** [comment]
I don't have stat data for mopub, as I often get NO_FILL in my own test.

But I do have some stat data for AdMob, you can find it in the AdMob plugin homepage, see:
https://github.com/floatinghotpot/cordova-admob-pro#tips

**Comment by Malikfida** [comment]
I have implemented Mopub on one of my android application but sadly it is not showing Ads when application is live. It was showing Ads in test phase. I contacted mopub team and did not get any response yet. I have been getting message on my applications.
"Banners fauked to load. No Ads found."
It seems mopub is a huge mess.
